export enum ENavigationMenu {
  DASHBOARD = "DASHBOARD",
  PROGRAMS = "PROGRAMS",

  MESSAGES_CREATE_NEW_MESSAGE = "MESSAGES_CREATE_NEW_MESSAGE",
  MESSAGES_DRAFTS = "MESSAGES_DRAFTS",
  MESSAGES_SCHEDULED = "MESSAGES_SCHEDULED",
  MESSAGES_EMAIL_SENT = "MESSAGES_EMAIL_SENT",

  CONTENT_IMAGES = "CONTENT_IMAGES",
  CONTENT_HTML_CONTENT = "CONTENT_HTML_CONTENT",
 
  CONTACTS_CREATE_CONTACT = "CONTACTS_CREATE_CONTACT",
  CONTACTS_CONTACT_PROFILE = "CONTACTS_CONTACT_PROFILE",
  CONTACTS_SEARCH_CONTACTS = "CONTACTS_SEARCH_CONTACTS",
}
